### ISSUE TITLE
Possibility of making this VR?

### ISSUE THREAD

**Issue by malani-art** [mister-blanket/kin-cloud#20]
Hi! I've been using Blood-lines and am very happy with it so far - thank you for making this! I have reached a point in my project where I am thinking of displaying it via VR. This may be far fetched but I'm quite new to this - is there a possibility of activating VR compatibility?

Thank you

**Comment by oh-kay-blanket** [comment]
Glad you're liking it. Great question! I haven't worked with VR so I cannot offer much in the way of specific guidance. However, I'm currently using https://github.com/vasturiano/3d-force-graph for the visualizer implementation. I can see that the owner made a VR version of the viewer at https://github.com/vasturiano/3d-force-graph-vr. It looks like the graph implementation is quite similar. I think a starting place would be to look at Graph.js (in blood-lines) and try swapping out line 4 for the VR version of FroceGraph3D. Hope that at least gives some starting direction.

**Comment by malani-art** [comment]
@mister-blanket thank you for your response! I tried doing that a few days ago and just again now (in fact, I posted a question for vasturiano (https://github.com/vasturiano/3d-force-graph-vr/issues/26)) but I get a wall of errors. I'm not sure how to proceed with this - it seems like some compatibility issue between A-frame and three.js?

**Comment by oh-kay-blanket** [comment]
No current plan to adapt to VR
