### ISSUE TITLE
Interactivity does not work!

### ISSUE THREAD

**Issue by malani-art** [mister-blanket/kin-cloud#27]
Hello! I am facing a very odd issue where enabling drag does not work. Also, clicking on the node does not do anything. I'm very confused. **I haven't made any changes to the code**. This is a fresh code download.

**Comment by oh-kay-blanket** [comment]
@malani-art I believe the click issue is fixed. Can you pull and test again? As for the node drag, I don't think that will work in this program as I have to assign the nodes to specific Y values to properly map birth dates along the timeline. What is it that you were hoping to do with drag?
