### ISSUE TITLE
Support for Webtrees data

### ISSUE THREAD

**Issue by SvbZ3r0** [mister-blanket/kin-cloud#31]
I tried the program with a GEDCOM file exported from [Webtrees](https://webtrees.net/). I see all the people in there, but no links. Nothing showing who is who's son or wife or whatnot.
Webtrees is pretty popular, and I don't think they use a specialized version of GEDCOM (although I'm not too sure). Could you take a look?

**Comment by oh-kay-blanket** [comment]
Hi there. I'm not familiar with Webtrees, but I'll contact their admin to see if they can share some sample GEDCOM exports from it for me to look into. If you have any sample data you've exported from there that you are willing to share, I'd be happy to test that out too.

**Comment by oh-kay-blanket** [comment]
@SvbZ3r0 I believe I have resolved the issue. Would you mind trying now and let me know if it works?

**Comment by SvbZ3r0** [comment]
Hey thanks for looking into this. I'll take a look when I have the time and I'll let you know if it works now.
