### ISSUE TITLE
Possible bug in GEDCOM file reading?

### ISSUE THREAD

**Issue by jacobjivanov** [mister-blanket/kin-cloud#35]
I decided to use the Blood Lines tool today and noticed that one person was displayed WAY off of the rest of everybody else. I clicked on them, and it said they were born 996, rather than the correct 1996. Wanting to make sure it wasn't a typo in my tree, I checked, and the correct date was entered.  then checked the GEDCOM file itself. I'm not sure exactly what is going wrong.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/59805681/209032913-79314be1-fdd9-4468-b212-af60b41ef4dc.png">

<img width="692" alt="image" src="https://user-images.githubusercontent.com/59805681/209032713-814afc7b-c7ae-4cc2-8540-06a434a81df0.png">

**Comment by oh-kay-blanket** [comment]
Interesting. I tried using that exact date in one of my other files and saw no issue. I'm not sure offhand what may be causing that. Would you be open to sharing a file or just that individual for me to investigate?

![Screen Shot 2022-12-31 at 3 43 58 PM](https://user-images.githubusercontent.com/25814886/210156159-2ecd9efa-952f-44f3-9755-bb4c95f42b0d.png)

**Comment by oh-kay-blanket** [comment]
Unable to reproduce
